image: golang:latest

variables:
  OUTPUT_NAME: backend-main

stages:
  - lint
  - build

before_script:
  - echo "before_script"
  - git version
  - go version
  - go env -w GO111MODULE=on
  - go env -w GOPROXY="https://goproxy.io,direct"

golangci-lint:
  tags:
    - unilab-backend-runner
  image: golangci/golangci-lint:v1.46.1
  stage: lint
  allow_failure: true
  script:
    - $(go env GOPATH)/bin/golangci-lint run -v -E gofmt -E revive -E gocyclo -E misspell -E cyclop -E gocritic ./...

compile-server:
  tags:
    - unilab-backend-runner
  stage: build
  script:
    - go mod download
    - go build -race -ldflags="-s -w" -o $OUTPUT_NAME
  artifacts:
    paths:
      - $OUTPUT_NAME

compile-sandbox:
  tags:
    - unilab-backend-runner
  stage: build
  script:
    - g++ ./third_party/vfk_uoj_sandbox/run_program.cpp -o ./prebuilt/uoj_run -O2 -Werror -Wfatal-errors -Wall -Wextra
    - g++ ./third_party/testlib/fcmp.cpp -o ./prebuilt/fcmp -O2 -Werror -Wfatal-errors -Wall -Wextra
