version: '3'
# version see: https://docs.docker.com/compose/compose-file/compose-versioning/
services:

  unilab-nginx:
    container_name: unilab-nginx
    image: nginx
    restart: always
    depends_on: 
      - unilab-backend1
      - unilab-backend2
      - unilab-backend3
    links:
      - unilab-backend1:unilab-backend1
      - unilab-backend2:unilab-backend2
      - unilab-backend3:unilab-backend3
    ports: 
      - 8001:80
    environment:
      TZ: 'Asia/Shanghai'
    volumes: 
    #  docker cp unilab-nginx:/usr/share/nginx/html ./nginx/html
    #  docker cp unilab-nginx:/etc/nginx/conf.d ./nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/html:/etc/nginx/html
      - /d/unilab-backend-mount/nginx/logs:/var/log/nginx

  unilab-mysql:
    container_name: unilab-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
    ports: 
      - 3307:3306
    volumes: 
      - /d/mysql-docker:/var/lib/mysql
      - ./mysql:/mysql-scripts

  unilab-backend1:
    container_name: unilab-backend1
    build: .
    depends_on:
      - unilab-mysql
    restart: always
    links:
      - unilab-mysql:mysql
    volumes: 
      - /d/unilab-backend-mount/server1-runtime:/unilab-files/runtime
      - /d/unilab-backend-mount/upload:/unilab-files/upload
    cap_add:
     - SYS_PTRACE

  unilab-backend2:
    container_name: unilab-backend2
    build: .
    depends_on:
      - unilab-mysql
    restart: always
    links:
      - unilab-mysql:mysql
    volumes: 
      - /d/unilab-backend-mount/server2-runtime:/unilab-files/runtime
      - /d/unilab-backend-mount/upload:/unilab-files/upload
    cap_add:
     - SYS_PTRACE
      
  unilab-backend3:
    container_name: unilab-backend3
    build: .
    depends_on:
      - unilab-mysql
    restart: always
    links:
      - unilab-mysql:mysql
    volumes: 
      - /d/unilab-backend-mount/server3-runtime:/unilab-files/runtime
      - /d/unilab-backend-mount/upload:/unilab-files/upload
    cap_add:
     - SYS_PTRACE
